apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: site
          image: thiagofh/conversao-temperatura:v1
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 8080
  type: NodePort

